### ISSUE TITLE
JSON-RPC Error when running private transaction

### ISSUE THREAD

**Issue by thomastomy5** [ConsenSys/quorum#1409]
#### System information

OS & Version: Ubuntu 22.04 LTS (GNU/Linux 5.15.0-1004-aws x86_64)

#### Steps to reproduce the behaviour 
node scripts/private_tx.js

#### Backtrace

````
ubuntu@ip-172-31-7-89:~/quorum-test-network/smart_contracts/privacy$ node scripts/private_tx.js
Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (/home/ubuntu/quorum-test-network/smart_contracts/privacy/node_modules/web3-core-helpers/lib/errors.js:43:16)
    at XMLHttpRequest.request.onreadystatechange (/home/ubuntu/quorum-test-network/smart_contracts/privacy/node_modules/web3-providers-http/lib/index.js:95:32)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/ubuntu/quorum-test-network/smart_contracts/privacy/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/home/ubuntu/quorum-test-network/smart_contracts/privacy/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpRequestError (/home/ubuntu/quorum-test-network/smart_contracts/privacy/node_modules/xhr2-cookies/dist/xml-http-request.js:349:14)
    at ClientRequest.<anonymous> (/home/ubuntu/quorum-test-network/smart_contracts/privacy/node_modules/xhr2-cookies/dist/xml-http-request.js:252:61)
    at ClientRequest.emit (node:events:527:28)
    at Socket.socketErrorListener (node:_http_client:454:9)
    at Socket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
````

**Comment by antonydenyer** [comment]
Can you paste the logs from `member1quorum` node
