### ISSUE TITLE
Production quorum node got exited with error - runtime/cgo: pthread_create failed: Resource temporarily unavailable

### ISSUE THREAD

**Issue by Purbaja** [ConsenSys/quorum#1579]
In a production environment one quorum node suddenly got exited with error - "runtime/cgo: pthread_create failed: Resource temporarily unavailable" 

raft2022/12/05 01:31:15.107297 INFO: 13 [term: 5960] ignored a MsgHeartbeat message with lower term from e [term: 5959]
raft2022/12/05 01:31:15.107487 INFO: 13 [term: 5960] ignored a MsgHeartbeat message with lower term from e [term: 5959]
runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x7f7d043bf9ee m=2 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7f7d043bf9ee
stack: frame={sp:0x7f7d02109508, fp:0x0} stack=[0x7f7d020e9e38,0x7f7d02109a38)
00007f7d02109408: 0000000000000037 0000000000000000
00007f7d02109418: 0000000000000000 0000000000000000
00007f7d02109428: 0000000000000001 00007f7d0440d0c0
00007f7d02109438: 0000000000000037 00007f7d044100a8
00007f7d02109448: 00007f7d02109480 00007f7d02109510

There were many other errors also. Some of the errors we observed in quorum logs -

goroutine 826 [IO wait, 2 minutes]:
internal/poll.runtime_pollWait(0x7f7d01cc32a0, 0x72, 0xffffffffffffffff)
        /usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc09a5cc998, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)

github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/pkg/transport.timeoutConn.Read(0x1835220, 0xc0868154a8, 0x0, 0x0, 0xc09b578000, 0x1000, 0x1000, 0xc016f87e00, 0x4, 0xc07deecb68)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/pkg/transport/timeout_conn.go:43 +0x5d
net/http.(*persistConn).Read(0xc099404ea0, 0xc09b578000, 0x1000, 0x1000, 0xc098fed4a0, 0xc07deecc20, 0x41ed15)
        /usr/local/go/src/net/http/transport.go:1758 +0x75

goroutine 851 [select, 2 minutes]:
net/http.(*persistConn).writeLoop(0xc099404ea0)

goroutine 3008147 [chan receive, 2865 minutes]:
github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/rafthttp.(*streamHandler).ServeHTTP(0xc078b66d00, 0x181f8c0, 0xc0230ceee0, 0xc04be2da00)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/rafthttp/http.go:331 +0xbff
net/http.(*ServeMux).ServeHTTP(0xc078b66d40, 0x181f8c0, 0xc0230ceee0, 0xc04be2da00)
        /usr/local/go/src/net/http/server.go:2387 +0x1bd

**Comment by baptiste-b-pegasys** [comment]
apparently it cannot connect to etcd service, doesn't it run correctly?

**Comment by Purbaja** [comment]
Yes.. The node was up and running for more than a year. suddenly it exited with the above errors.
Few more informations-
1. Current block height - 44949795
2. Recent change was - Few contract listeners were subscribed in the production to listen events from contract.

Any idea what could cause this quorum container to exit? Any impact by contract listener?

**Comment by Purbaja** [comment]
@baptiste-b-pegasys Below is the detailed error log when container got exited:

raft2022/12/05 00:11:12.579798 INFO: raft.node: 13 elected leader e at term 5959
raft2022/12/05 01:31:15.078224 INFO: 13 [term: 5959] received a MsgVote message with higher term from 4 [term: 5960]
raft2022/12/05 01:31:15.078261 INFO: 13 became follower at term 5960
raft2022/12/05 01:31:15.078273 INFO: 13 [logterm: 5959, index: 44950568, vote: 0] cast MsgVote for 4 [logterm: 5959, index: 44950568] at term 5960
raft2022/12/05 01:31:15.078282 INFO: raft.node: 13 lost leader e at term 5960
raft2022/12/05 01:31:15.099078 INFO: raft.node: 13 elected leader 4 at term 5960
raft2022/12/05 01:31:15.107297 INFO: 13 [term: 5960] ignored a MsgHeartbeat message with lower term from e [term: 5959]
raft2022/12/05 01:31:15.107487 INFO: 13 [term: 5960] ignored a MsgHeartbeat message with lower term from e [term: 5959]
runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x7f7d043bf9ee m=2 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7f7d043bf9ee
stack: frame={sp:0x7f7d02109508, fp:0x0} stack=[0x7f7d020e9e38,0x7f7d02109a38)
00007f7d02109408:  0000000000000037  0000000000000000
00007f7d02109418:  0000000000000000  0000000000000000
00007f7d02109428:  0000000000000001  00007f7d0440d0c0
00007f7d02109438:  0000000000000037  00007f7d044100a8
00007f7d02109448:  00007f7d02109480  00007f7d02109510
00007f7d02109458:  00007f7d043c6207  0000000000000000
00007f7d02109468:  00000000018ac3be  00007f7d00000000
00007f7d02109478:  00007f7d02109498  0000003000000010
00007f7d02109488:  00007f7d021096e0  00007f7d02109610
00007f7d02109498:  0000000000000000  0000000000000000
00007f7d021094a8:  0000000000000000  0000000000000000
00007f7d021094b8:  0000000000000000  5f64616572687470
00007f7d021094c8:  6620657461657263  52203a64656c6961
00007f7d021094d8:  20656372756f7365  7261726f706d6574
00007f7d021094e8:  76616e7520796c69  00656c62616c6961
00007f7d021094f8:  0000000000000000  00000000018ac3be
00007f7d02109508: <00007f7d043bfb49  0000000000000000
00007f7d02109518:  00007f7d043afd61  0000000000000000
00007f7d02109528:  00007f7cdae93000  00007f7cdae93000
00007f7d02109588:  00007f7d0440d14c  00007f7d021097b0
00007f7d02109598:  00007f7d021098c0  00007f7d0440d0c0
00007f7d021095a8:  00007f7d0439772a  00007f7d043deba0
00007f7d021095b8:  0a007f7d021098c0  00007f7d0440d0c0
00007f7d021095c8:  00007f7d043c2371  00007f7d021098c0
00007f7d021095d8:  00007f7d0440d0c0  00000000018ac3be
00007f7d021095e8:  000000000115392a  0000003000000008
00007f7d021095f8:  00007f7d021096e0  00007f7d02109610
runtime: unknown pc 0x7f7d043bf9ee
stack: frame={sp:0x7f7d02109508, fp:0x0} stack=[0x7f7d020e9e38,0x7f7d02109a38)
00007f7d02109408:  0000000000000037  0000000000000000
00007f7d02109418:  0000000000000000  0000000000000000
00007f7d02109428:  0000000000000001  00007f7d0440d0c0
00007f7d02109438:  0000000000000037  00007f7d044100a8
00007f7d02109448:  00007f7d02109480  00007f7d02109510
00007f7d02109458:  00007f7d043c6207  0000000000000000
00007f7d02109468:  00000000018ac3be  00007f7d00000000
00007f7d02109478:  00007f7d02109498  0000003000000010
00007f7d02109488:  00007f7d021096e0  00007f7d02109610
00007f7d021095e8:  000000000115392a  0000003000000008
00007f7d021095f8:  00007f7d021096e0  00007f7d02109610

goroutine 1 [chan receive, 4273 minutes]:
github.com/ethereum/go-ethereum/node.(*Node).Wait(0xc00042e500)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/node/node.go:504 +0x7c
main.geth(0xc0005e2000, 0x0, 0x0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:351 +0x183
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0x12be160, 0x15f0d88, 0xc0005e2000, 0xc0000c43c0, 0x0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:490 +0xc8
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc000300680, 0xc0000c6000, 0x24, 0x24, 0x0, 0x0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:264 +0x58c
main.main()
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:276 +0x55

goroutine 20 [chan receive, 4273 minutes]:
github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.(*nonrecursiveTree).dispatch(0xc0000c4540, 0xc0000c4480)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:36 +0xb6
created by github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.newNonrecursiveTree
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:29 +0xdc

goroutine 21 [chan receive, 4273 minutes]:
github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.(*nonrecursiveTree).internal(0xc0000c4540, 0xc0000c44e0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:81 +0x58
created by github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.newNonrecursiveTree
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:30 +0x108

goroutine 22 [syscall, 4273 minutes]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 23 [chan receive, 2 minutes]:
github.com/ethereum/go-ethereum/metrics.(*meterArbiter).tick(0x2850dc0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/metrics/meter.go:289 +0x78
created by github.com/ethereum/go-ethereum/metrics.NewMeterForced
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/metrics/meter.go:70 +0x104

goroutine 24 [select, 2 minutes]:
github.com/ethereum/go-ethereum/consensus/ethash.(*Ethash).remote(0xc0001081c0, 0x0, 0x0, 0x0, 0x0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/consensus/ethash/sealer.go:307 +0x532
created by github.com/ethereum/go-ethereum/consensus/ethash.New
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/consensus/ethash/ethash.go:496 +0x35c

goroutine 25 [select, 4 minutes]:
github.com/ethereum/go-ethereum/vendor/github.com/patrickmn/go-cache.(*janitor).Run(0xc00016f700, 0xc0001a1280)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/patrickmn/go-cache/cache.go:1037 +0x106
created by github.com/ethereum/go-ethereum/vendor/github.com/patrickmn/go-cache.runJanitor
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/patrickmn/go-cache/cache.go:1056 +0x70

goroutine 26 [chan receive, 2 minutes]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc00016f7a0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_cacher.go:55 +0x9f

goroutine 27 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc00016f7a0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_cacher.go:55 +0x9f

goroutine 28 [chan receive, 2 minutes]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc00016f7a0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_cacher.go:55 +0x9f

**Comment by baptiste-b-pegasys** [comment]
if you are on a cloud managed kubernetes, sometimes maintenance requires to move VM and bad things happen. Pod were maybe killed by the k8s orchestration.

You can request logs of cloud maintenance around the time the node were killed

**Comment by Purbaja** [comment]
Hi @baptiste-b-pegasys Thanks for the reply, but in our case the VM was not restarted. Both tessera and quorum docker containers were running in that VM, and only quorum container got exited with above error.

In such scenario what else can we check?

**Comment by baptiste-b-pegasys** [comment]
Should take a look at `runtime/cgo: pthread_create failed: Resource temporarily unavailable`

1. https://github.com/docker/for-linux/issues/343
2. https://groups.google.com/g/golang-nuts/c/8gszDBRZh_4
3. https://phabricator.wikimedia.org/T206215
4. https://golang-nuts.narkive.com/ZFu7HiOn/go-nuts-getting-runtime-cgo-pthread-create-failed-resource-temporarily-unavailable-crashes

seems that many systems exhausted the ressources of the system. Some ressource stress appeared?
Enough memory?

Some metrics or graphs could provide a clue here?

but as for `runtime: unknown pc 0x7f7d043bf9ee`: seems that the memory has changed or was not accessible.

I found only windows 10 related bugs (https://github.com/golang/go/issues/20846)

it's possible that a VM moves due to maintenance, it depends of the cloud provider, weird behaviors can happen. Once a year, it's not big.

**Comment by Purbaja** [comment]
@baptiste-b-pegasys in the same network we are observing sudden restart for other quorum nodes also in last couple of days. The error there getting logged is only 'Killed' . I have created a separate ticket also - https://github.com/ConsenSys/quorum/issues/1580

Only thing we could found from the Azure log analytics is  that the Logical Disk MB/s (read-write operations from the Disk) is extending beyond the supported capacity of the VM. Supported capacity is 64 MB/s whereas actual has a spike of 133 MB/s which is when the Quorum container got restarted.

So, which operation can cause this spike of logical disk MB/s. In the last month we started multiple contract listeners in this quorum network. Can these event listeners cause this spike ?
