### ISSUE TITLE
Node panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by SecTechTool** [ConsenSys/quorum#1589]
#### System information

version: master
OS & Version: Linux
Commit hash : 56184d8367be7109cfd76ba4896d841801c66520

#### Expected behaviour
Nodes run as usual.

#### Actual behaviour
Nodes crash down, and can not be recovered.

#### Steps to reproduce the behaviour
Setup a QBFT network locally, following the instruction in https://consensys.net/docs/goquorum/en/latest/tutorials/private-network/create-qbft-network. Repeatedly sending fuzzed consensus messages to node-2.

#### Backtrace

Root location:
https://github.com/ConsenSys/quorum/blob/master/eth/downloader/downloader.go
```
header := d.lightchain.GetHeaderByHash(h) // Independent of sync mode, header surely exists
if header.Number.Uint64() != check {
	p.log.Warn("Received non requested header", "number", header.Number, "hash", header.Hash(), "request", check)
	return 0, fmt.Errorf("%w: non-requested header (%d)", errBadPeer, header.Number)
}
start = check
hash = h
```
In line 1004, nil pointer in header.Number.Uint64() .

log info:
````
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10472ad00]


goroutine 75621 [running]:
github.com/ConsenSys/quorum/eth/downloader.(*Downloader).findAncestorBinarySearch(0x14006fa1c20, 0x14019ff0000, 0x100000001, 0xbcfc99, 0xbb9cb3, 0xbb9cb3, 0x0, 0x10509bcd8)
	github.com/ConsenSys/quorum/eth/downloader/downloader.go:1004 +0x440
github.com/ConsenSys/quorum/eth/downloader.(*Downloader).findAncestor(0x14006fa1c20, 0x14019ff0000, 0x14025d5a480, 0x1400067ab40, 0x0, 0x0)
	github.com/ConsenSys/quorum/eth/downloader/downloader.go:856 +0x338
github.com/ConsenSys/quorum/eth/downloader.(*Downloader).syncWithPeer(0x14006fa1c20, 0x14019ff0000, 0x93275d9e27d9cc81, 0x20880d02a23dad6b, 0xefba04bd94c4dbfb, 0x632ca43bf48c30be, 0x1404d8ac5c0, 0x0, 0x0)
	github.com/ConsenSys/quorum/eth/downloader/downloader.go:513 +0x3c0
github.com/ConsenSys/quorum/eth/downloader.(*Downloader).synchronise(0x14006fa1c20, 0x1403876e040, 0x40, 0x93275d9e27d9cc81, 0x20880d02a23dad6b, 0xefba04bd94c4dbfb, 0x632ca43bf48c30be, 0x1404d8ac5c0, 0x1, 0x0, ...)
	github.com/ConsenSys/quorum/eth/downloader/downloader.go:469 +0x31c
github.com/ConsenSys/quorum/eth/downloader.(*Downloader).Synchronise(0x14006fa1c20, 0x1403876e040, 0x40, 0x93275d9e27d9cc81, 0x20880d02a23dad6b, 0xefba04bd94c4dbfb, 0x632ca43bf48c30be, 0x1404d8ac5c0, 0x23ac5c4400000002, 0x8b4b0ae95c9805f1, ...)
	github.com/ConsenSys/quorum/eth/downloader/downloader.go:356 +0x6c
github.com/ConsenSys/quorum/eth.(*handler).doSync(0x140073c0000, 0x1403937e0c0, 0x1403c7781c0, 0x1c738c98100323fe)
	github.com/ConsenSys/quorum/eth/sync.go:331 +0x100
github.com/ConsenSys/quorum/eth.(*chainSyncer).startSync.func1(0x14006efd950, 0x1403937e0c0)
	github.com/ConsenSys/quorum/eth/sync.go:307 +0x34
created by github.com/ConsenSys/quorum/eth.(*chainSyncer).startSync
	github.com/ConsenSys/quorum/eth/sync.go:307 +0x78
````
.

**Comment by baptiste-b-pegasys** [comment]
I think this is reproducible in the go-ethereum version as well because it's not quorum specific code.

https://github.com/ethereum/go-ethereum/blob/master/eth/downloader/downloader.go#L971

If you are able to reproduce this with go-ethereum, you might raise an issue there too.

I/You can add a check on the header by raising an error that it's missing
